# Blueprint Konfigurasi Final untuk Render

services:
  # Bagian ini mendefinisikan Web Service (aplikasi Laravel) kita
  - type: web
    name: inventory-toko-material
    plan: free
    branch: main
    # Perintah-perintah ini akan dijalankan di dalam lingkungan PHP
    buildCommand: "composer install --optimize-autoloader --no-dev; php artisan config:cache; php artisan route:cache"
    startCommand: "heroku-php-apache2 public/"
    envVars:
      # PENTING: Memaksa Render menggunakan Buildpack PHP
      - key: BUILDPACK_URL
        value: https://github.com/heroku/heroku-buildpack-php
      # Variabel Laravel Anda
      - key: APP_KEY
        value: "base64:1GccOh1rt21SJl9AY8NL2KMy/kLOaOuF8RoKgZkwMVc=" # GANTI DENGAN APP_KEY ANDA JIKA BERBEDA
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      # Variabel ini akan otomatis terhubung ke database yang sudah kita buat
      - key: DATABASE_URL
        fromDatabase:
          name: db-inventory # Pastikan nama ini sama dengan nama database Anda di Render
          property: connectionString

databases:
  # Bagian ini mendefinisikan database kita
  - name: db-inventory # Pastikan nama ini sama dengan nama database Anda di Render
    plan: free
